version: "3"

services:
  backend:
    container_name: backend-microsaas
    restart: always
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    build:
      context: "."
      dockerfile: ./Dockerfile.txt
    ports:
      - "3005:8000"
    # volumes:
    #   - ./files:/MicroSaaS
